  version: '3'

  services:
    # db:
    #   image: postgres
    #   environment:
    #     - POSTGRES_DB=postgres
    #     - POSTGRES_USER=postgres
    #     - POSTGRES_PASSWORD=postgres
    app:
      build: .
      command: python main.py
      # env_file:
      #   - ./.env.dev
      volumes:
        - ./game:/code
      ports:
        - "8000:8000"
      # depends_on:
      #   - db